# Generated by Django 3.1.2 on 2020-10-29 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
